name: flutter_bloc_tdd_clean_architecture
description: "🚀 A comprehensive guide to mastering Flutter with BLoC state management, Test-Driven Development (TDD), and Clean Architecture. This repository showcases how to build scalable, maintainable, and testable applications by applying best practices and solid design principles. Explore how to structure your app using BLoC, write effective unit and widget tests, and implement Clean Architecture to keep your codebase clean and organized."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^8.1.2
  font_awesome_flutter: ^10.7.0
  get_it: ^8.0.0
  iconly: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.0.0
  open_file: ^3.5.8
  path_provider: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  swipe_to: ^1.0.6
  url_launcher: ^6.3.1
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3
  chewie: ^1.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/icons/
    - assets/lottie/
    - assets/images/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800